### ISSUE TITLE
growingio-java-sdk 1.0.6 无法安装

### ISSUE THREAD

**Issue by leo302323** [growingio/growingio-java-sdk#29]
### 描述你的问题以及如何重现

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'io.growing.sdk.java:growingio-java-sdk:1.0.6'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

### 请提供您看到的异常或错误

```true
gradle install 后 报：
Could not resolve io.growing.sdk.java:growingio-java-sdk:1.0.6
```

**Comment by styluo** [comment]
感谢指出问题，项目中maven的pom.xml不符合最佳实践, version使用占位符指定, 并且使用了profile及activeByDefault指定, gradle解析时对profile的支持如下
```
Profiles that are active by default (available with Gradle 1.12 and higher)
Profiles that are active on the absence of a system property (available with Gradle 2.0 and higher)
```
导致gradle认为version版本号为1.0.6-SNAPSHOT, 与实际依赖版本不符合
gradle对maven pom profile的支持范围参考 https://blog.gradle.org/maven-pom-profiles

这个问题在github ci中通过mvn versions:set解决，我们后续通过ci发个新版本解决该问题

**Comment by styluo** [comment]
1.0.7版本已经通过github ci发版，测试没有问题，sonatype已经release，等待同步到maven central后可集成1.0.7版本
